env:
  browser: true
  es2020: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  import/extensions: 0
  import/prefer-default-export: 0
  prefer-destructuring: 0
